name = "LeanMachineLearning"
defaultTargets = ["LeanMachineLearning"]
lintDriver = "batteries/runLinter"

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false
# Enable all mathlib linters: automatically matches what mathlib uses.
weak.linter.mathlibStandardSet = true

[[require]]
name = "verso"
git = "https://github.com/leanprover/verso"
rev = "v4.33.0"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "63025c440a76f080d28ec38a8469e53d46809926"

[[lean_lib]]
name = "LeanMachineLearning"

[[lean_lib]]
name = "LMLTutorial"
globs = ["LMLTutorial.*"]

[[lean_exe]]
name = "tutorial"
srcDir = "LMLTutorial/"
root = "Tutorial"
